version: "3.8"

services:
  frontend:
    build: ./crop-planner
    ports:
      - "3001:3001"
    container_name: frontend
    restart: always
    links:
      - backend
    restart: always

  backend:
    build: ./soil-service
    ports:
      - "3000:3000"
    container_name: backend
    restart: always
